name 'jlondon-githubkey'
version '0.0.2'
source 'UNKNOWN'
author 'Justice London'
license 'Apache License, Version 2.0'
summary 'Authorized_key module which pulls information from github'
description 'This module allows you to specify an array of github usernames and pull down their public key information from github'
project_page 'https://github.com/justicel/puppet-githubkey'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
